services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-startup-analyzer-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: ai-startup-analyzer-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

    restart: unless-stopped